nome = prompt("Qual é o nome do vinho? ")
tipo = prompt("Qual é o tipo do vinho? ")
safra = prompt("Qual é a safra do vinho? ")
quantidade = prompt("Qual é a quantidade de vinhos? ")
console.log([nome, tipo, safra, quantidade])
